"""Analytical model of the MPI traffic a circuit will generate.

The model answers one question: given which logical qubits are placed on
global (rank-selecting) positions, how many bytes and how many messages will
the distributed runtime produce?

It is deliberately **gate-role aware**. "Is the qubit global?" is not enough,
because the runtime treats a global qubit very differently depending on the
gate:

* a diagonal gate never communicates, wherever its operands sit;
* a control qubit is only read, so a global control costs nothing extra;
* a target qubit is written, and writing a global bit moves amplitudes.

Costs are expressed in **bytes**, not arbitrary scores, so predictions can be
compared directly against the measured counters from
`CommunicationProfiler`. `tests/mpi/test_cost_model_prediction.py` asserts
that they agree exactly.

Accounting convention
---------------------
`bytes_transferred` counts payload **sent**, summed over all ranks. Each
pairwise exchange is symmetric, so the same number of bytes is received; the
estimate reports sends to stay comparable with `metrics()["bytes_sent"]`.
"""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from dataclasses import dataclass, field
from typing import Any

from aegisq.circuit.circuit import Circuit
from aegisq.circuit.gates import GATE_SPECS, Gate

#: Bytes per complex amplitude.
AMPLITUDE_BYTES = {"fp64": 16, "fp32": 8}


@dataclass(frozen=True)
class GateCost:
    """Traffic generated by one gate, summed over the ranks that take part."""

    bytes_sent: int = 0
    exchanges: int = 0
    participating_ranks: int = 0
    message_bytes: int = 0

    @property
    def communicates(self) -> bool:
        return self.exchanges > 0


@dataclass(frozen=True)
class CommunicationEstimate:
    """Predicted traffic for a whole circuit under one placement."""

    global_qubits: tuple[int, ...]
    bytes_sent: int
    pairwise_exchanges: int
    communicating_gates: int
    world_size: int
    shard_bytes: int
    per_opcode: dict[str, dict[str, int]] = field(default_factory=dict)

    @property
    def gibibytes(self) -> float:
        return self.bytes_sent / 2**30

    def summary(self) -> str:
        return (
            f"global qubits {list(self.global_qubits)}: "
            f"{self.bytes_sent / 2**20:.2f} MiB in "
            f"{self.pairwise_exchanges} exchanges "
            f"({self.communicating_gates} communicating gates)"
        )

    def as_dict(self) -> dict[str, Any]:
        return {
            "global_qubits": list(self.global_qubits),
            "bytes_sent": self.bytes_sent,
            "pairwise_exchanges": self.pairwise_exchanges,
            "communicating_gates": self.communicating_gates,
            "world_size": self.world_size,
            "shard_bytes": self.shard_bytes,
            "per_opcode": self.per_opcode,
        }


def default_global_qubits(num_qubits: int, world_size: int) -> tuple[int, ...]:
    """The placement the runtime uses when nobody chooses one.

    The identity mapping puts logical qubit `q` at physical position `q`, so
    the highest-numbered qubits end up on the global positions.
    """
    p = (world_size - 1).bit_length() if world_size > 1 else 0
    if world_size & (world_size - 1):
        raise ValueError(f"world size must be a power of two, got {world_size}")
    return tuple(range(num_qubits - p, num_qubits)) if p else ()


def mapping_from_global_qubits(num_qubits: int, global_qubits: Iterable[int]) -> list[int]:
    """Build a logical-to-physical permutation placing `global_qubits` on ranks.

    Local qubits keep their relative order on the low positions, and the
    chosen global qubits take the high positions in ascending order. Positions
    inside each group do not affect communication volume, so any consistent
    convention will do; this one keeps mappings readable and reproducible.
    """
    chosen = sorted(set(global_qubits))
    for q in chosen:
        if not 0 <= q < num_qubits:
            raise ValueError(f"qubit {q} out of range for {num_qubits} qubits")
    locals_ = [q for q in range(num_qubits) if q not in set(chosen)]
    mapping = [0] * num_qubits
    for position, qubit in enumerate(locals_):
        mapping[qubit] = position
    for offset, qubit in enumerate(chosen):
        mapping[qubit] = len(locals_) + offset
    return mapping


class CommunicationCostModel:
    """Predicts distributed traffic for a given world size and precision."""

    def __init__(self, num_qubits: int, world_size: int, precision: str = "fp64") -> None:
        if world_size < 1 or world_size & (world_size - 1):
            raise ValueError(f"world size must be a power of two, got {world_size}")
        if precision not in AMPLITUDE_BYTES:
            raise ValueError(f"unknown precision {precision!r}; use 'fp64' or 'fp32'")

        self.num_qubits = num_qubits
        self.world_size = world_size
        self.precision = precision
        self.num_global_qubits = world_size.bit_length() - 1
        self.num_local_qubits = num_qubits - self.num_global_qubits
        if self.num_local_qubits < 1:
            raise ValueError(f"{num_qubits} qubits over {world_size} ranks leaves no local qubits")

        self.amplitude_bytes = AMPLITUDE_BYTES[precision]
        self.shard_amplitudes = 1 << self.num_local_qubits
        self.shard_bytes = self.shard_amplitudes * self.amplitude_bytes

    # -- per-gate rules -----------------------------------------------------

    def gate_cost(self, gate: Gate, global_qubits: frozenset[int]) -> GateCost:
        """Traffic for one gate, summed over the ranks that participate.

        The rules mirror `DistributedStateVectorT::apply_gate` one for one.
        """
        spec = GATE_SPECS[gate.opcode]

        # Diagonal gates scale amplitudes in place: never any communication.
        if spec.diagonal:
            return GateCost()

        if spec.num_qubits == 1:
            qubit = gate.qubits[0]
            if qubit not in global_qubits:
                return GateCost()
            # Every rank exchanges its whole shard with its partner.
            return GateCost(
                bytes_sent=self.shard_bytes * self.world_size,
                exchanges=self.world_size,
                participating_ranks=self.world_size,
                message_bytes=self.shard_bytes,
            )

        if gate.opcode == "cx":
            control, target = gate.qubits
            if target not in global_qubits:
                # A local target is written locally, whatever the control is.
                return GateCost()
            if control not in global_qubits:
                # Only control-set amplitudes move: half a shard, every rank.
                half = self.shard_bytes // 2
                return GateCost(
                    bytes_sent=half * self.world_size,
                    exchanges=self.world_size,
                    participating_ranks=self.world_size,
                    message_bytes=half,
                )
            # Global control: half the ranks skip the gate entirely, the rest
            # swap whole shards. Same total bytes, half as many messages.
            participants = self.world_size // 2
            return GateCost(
                bytes_sent=self.shard_bytes * participants,
                exchanges=participants,
                participating_ranks=participants,
                message_bytes=self.shard_bytes,
            )

        if gate.opcode == "swap":
            a, b = gate.qubits
            a_global, b_global = a in global_qubits, b in global_qubits
            if not a_global and not b_global:
                return GateCost()
            if a_global and b_global:
                participants = self.world_size // 2
                return GateCost(
                    bytes_sent=self.shard_bytes * participants,
                    exchanges=participants,
                    participating_ranks=participants,
                    message_bytes=self.shard_bytes,
                )
            half = self.shard_bytes // 2
            return GateCost(
                bytes_sent=half * self.world_size,
                exchanges=self.world_size,
                participating_ranks=self.world_size,
                message_bytes=half,
            )

        raise ValueError(f"no cost rule for opcode {gate.opcode!r}")

    # -- circuit level ------------------------------------------------------

    def estimate(
        self,
        circuit: Circuit,
        global_qubits: Sequence[int] | None = None,
    ) -> CommunicationEstimate:
        """Predicted traffic for `circuit` with the given global placement."""
        if global_qubits is None:
            global_qubits = default_global_qubits(self.num_qubits, self.world_size)
        chosen = frozenset(global_qubits)
        self._validate_global_set(chosen)

        total_bytes = 0
        total_exchanges = 0
        communicating = 0
        per_opcode: dict[str, dict[str, int]] = {}

        for gate in circuit:
            cost = self.gate_cost(gate, chosen)
            entry = per_opcode.setdefault(
                gate.opcode, {"gates": 0, "bytes_sent": 0, "exchanges": 0}
            )
            entry["gates"] += 1
            if cost.communicates:
                total_bytes += cost.bytes_sent
                total_exchanges += cost.exchanges
                communicating += 1
                entry["bytes_sent"] += cost.bytes_sent
                entry["exchanges"] += cost.exchanges

        return CommunicationEstimate(
            global_qubits=tuple(sorted(chosen)),
            bytes_sent=total_bytes,
            pairwise_exchanges=total_exchanges,
            communicating_gates=communicating,
            world_size=self.world_size,
            shard_bytes=self.shard_bytes,
            per_opcode=per_opcode,
        )

    def estimate_for_mapping(
        self, circuit: Circuit, mapping: Sequence[int]
    ) -> CommunicationEstimate:
        """Predicted traffic for an explicit logical-to-physical permutation."""
        if len(mapping) != self.num_qubits:
            raise ValueError("mapping must cover every logical qubit")
        global_qubits = [
            qubit for qubit, position in enumerate(mapping) if position >= self.num_local_qubits
        ]
        return self.estimate(circuit, global_qubits)

    def _validate_global_set(self, chosen: frozenset[int]) -> None:
        if len(chosen) != self.num_global_qubits:
            raise ValueError(
                f"{self.world_size} ranks need exactly {self.num_global_qubits} "
                f"global qubits, got {len(chosen)}"
            )
        for qubit in chosen:
            if not 0 <= qubit < self.num_qubits:
                raise ValueError(f"qubit {qubit} out of range")

    # -- fast path used by the optimiser ------------------------------------

    def compile_circuit(self, circuit: Circuit) -> CircuitCostProfile:
        """Pre-aggregate a circuit so candidate placements can be scored quickly.

        Scoring a placement gate by gate is O(gates) per candidate, which is
        wasteful inside a search over thousands of candidates. The aggregated
        form is O(n + swaps), and `test_cost_model.py` asserts the two agree.
        """
        return CircuitCostProfile.from_circuit(circuit, self)


@dataclass(frozen=True)
class CircuitCostProfile:
    """Circuit reduced to the counts the cost model actually needs."""

    model: CommunicationCostModel
    nondiagonal_single: tuple[int, ...]
    cx_by_target: tuple[int, ...]
    cx_pairs: tuple[tuple[int, int, int], ...]
    swap_pairs: tuple[tuple[int, int, int], ...]
    total_gates: int

    @classmethod
    def from_circuit(cls, circuit: Circuit, model: CommunicationCostModel) -> CircuitCostProfile:
        n = circuit.num_qubits
        nondiagonal = [0] * n
        cx_target = [0] * n
        cx_counts: dict[tuple[int, int], int] = {}
        swap_counts: dict[tuple[int, int], int] = {}

        for gate in circuit:
            spec = GATE_SPECS[gate.opcode]
            if spec.diagonal:
                continue
            if spec.num_qubits == 1:
                nondiagonal[gate.qubits[0]] += 1
            elif gate.opcode == "cx":
                control, target = gate.qubits
                cx_target[target] += 1
                cx_counts[(control, target)] = cx_counts.get((control, target), 0) + 1
            elif gate.opcode == "swap":
                pair = (min(gate.qubits), max(gate.qubits))
                swap_counts[pair] = swap_counts.get(pair, 0) + 1

        return cls(
            model=model,
            nondiagonal_single=tuple(nondiagonal),
            cx_by_target=tuple(cx_target),
            cx_pairs=tuple((c, t, n_) for (c, t), n_ in sorted(cx_counts.items())),
            swap_pairs=tuple((a, b, n_) for (a, b), n_ in sorted(swap_counts.items())),
            total_gates=len(circuit),
        )

    def bytes_for(self, global_qubits: Iterable[int]) -> int:
        """Total payload bytes for a candidate placement."""
        chosen = set(global_qubits)
        model = self.model
        shard = model.shard_bytes
        world = model.world_size

        total = 0
        for qubit in chosen:
            total += self.nondiagonal_single[qubit] * shard * world
            total += self.cx_by_target[qubit] * (shard // 2) * world
        for a, b, count in self.swap_pairs:
            if a in chosen or b in chosen:
                total += count * (shard // 2) * world
        return total

    def exchanges_for(self, global_qubits: Iterable[int]) -> int:
        """Total pairwise messages for a candidate placement.

        Bytes alone cannot distinguish a `CX` with a global control from one
        with a local control — both move the same volume — so the message
        count is tracked as a secondary, latency-flavoured objective.
        """
        chosen = set(global_qubits)
        model = self.model
        world = model.world_size

        total = 0
        for qubit in chosen:
            total += self.nondiagonal_single[qubit] * world
        for control, target, count in self.cx_pairs:
            if target in chosen:
                total += count * (world // 2 if control in chosen else world)
        for a, b, count in self.swap_pairs:
            a_global, b_global = a in chosen, b in chosen
            if a_global and b_global:
                total += count * (world // 2)
            elif a_global or b_global:
                total += count * world
        return total
